services:
  - type: web
    name: secure-token-login
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
